---
- name: Update package cache (Debian family)
  apt:
    update_cache: yes
    upgrade: yes
  when: ansible_facts['os_family'] == "Debian"

- name: Update package cache (RedHat family)
  dnf:
    name: "*"
    state: latest
  when: ansible_facts['os_family'] == "RedHat"

- name: Update package cache (Archlinux family)
  pacman:
    update_cache: yes
    upgrade: yes
  when: ansible_facts['os_family'] == "Archlinux"

- name: Enable and start system services
  service:
    name: "{{ item }}"
    enabled: yes
    state: started
  with_items: "{{ services }}"
  when: services is defined and services | length > 0

