---
- name: Enable and start system services
  service:
    name: "{{ item }}"
    enabled: yes
    state: started
  with_items: "{{ services }}"
  when: services is defined and services | length > 0

